// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlxzqcsmtszdnksbwcny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndseHpxY3NtdHN6ZG5rc2J3Y255Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMjM3NTUsImV4cCI6MjA1Nzg5OTc1NX0.GlAVfLt_Hc4lmk6GLYyhIYaS2bXrWhRsdJ7hoO3KmaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);